openapi: "3.0.0"
info:
  title: Dynamics Mobile API
  description:
  version: 1.0.0
  termsOfService: http://example.com/terms/

servers:
  - url: http://dynamicsmobile-agent-east1.us-east-1.elasticbeanstalk.com/api
  #- url: http://maisso04.dynamicsmobile.isystems.bg:8081/api
  #- url: http://localhost:5002/api


consumes:
  - application/json
produces:
  - application/json

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: dms-api-key
  schemas:
    GeneralError:
      type: object
      properties:
        success:
          type: boolean
          description: always false
        faultCode:
          type: string
          description: the code of the error
        faultstring:
          type: string
          description: description of the error
        requestUUID:
          type: string
          description: unique identifier of the error, which produced the error response
        rawErrror:
          type: string
          description: raw representation of the actual error in xml format
    InvoiceError:
      type: object
      properties:
        success:
          type: boolean
          description: always false
        faultCode:
          type: string
          description: the code of the error
        faultstring:
          type: string
          description: description of the error
        requestUUID:
          type: string
          description: unique identifier of the error, which produced the error response
        rawErrror:
          type: string
          description: raw representation of the actual error in xml format
        iic:
          type: string
          description: invoice issuer code generated by this middleware even if the remote service returns error
    WTNError:
      type: object
      properties:
        success:
          type: boolean
          description: always false
        faultCode:
          type: string
          description: the code of the error
        faultstring:
          type: string
          description: description of the error
        requestUUID:
          type: string
          description: unique identifier of the error, which produced the error response
        rawErrror:
          type: string
          description: raw representation of the actual error in xml format
        wtnic:
          type: string
          description: wtn invoice issuer code generated by this middleware even if the remote service returns error
    Unаuth:
      type: object
      properties:
        success:
          type: boolean
          description: always false
        message:
          type: string
          description: always contains the string Unauthorized

security:
  - ApiKeyAuth: []

paths:
  /plugins/alf/request/{appArea}/RegisterTCRRequest:
    post:
      summary: Sends RegisterTCRRequest towards the Albanian Fiscalization Service
      parameters:
        - in: path
          name: appArea
          schema:
            type: string
          required: true
          description: unique identifier of the Dynamics Mobile application area
          example: DEMO01
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                request:
                  type: string
                  description: xml representation of the RegisterTCRRequest according to the specification
              example:
                request: <RegisterTCRRequest xmlns="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema" xmlns:ns2="http://www.w3.org/2000/09/xmldsig#" Id="Request" Version="3"><Header SendDateTime="2021-04-10T08:43:00+02:00" UUID="e2caa8bc-91bf-429c-8919-e833367784c0" /><TCR BusinUnitCode="ge484ak993" IssuerNUIS="L01714012M" MaintainerCode="zk772ct263" SoftCode="cc476bs902" TCRIntID="2" ValidFrom="2021-04-10" Type="REGULAR" /></RegisterTCRRequest>
      responses:
        200:
          description: Successful TCR registration
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: always true
                  tcrCode:
                    type: string
                    description: the code of the TCR generated by the Tax Authorities
                    example: wk592ag291
                  requestUUID:
                    type: string
                    example: 8d216f9a-55bb-445a-be32-30137f11b964
                    description: unique identifier of the request

        400:
          description: TCR registration failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneralError"
              example:
                success: false
                faulCode: env:CLIENT
                faultstring: Client time differs from server time more than 60 minutes, difference is 4747 minutes.
                requestUUID: e2caa8bc-91bf-429c-8919-e833367784c0
                rawErrror: <env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/"><env:Header/><env:Body><env:Fault><faultcode>env:CLIENT</faultcode><faultstring>Client time differs from server time more than 60 minutes, difference is 4747 minutes.</faultstring><detail><code>2</code><requestUUID>e2caa8bc-91bf-429c-8919-e833367784c0</requestUUID><responseUUID>fe8ed7b6-48c7-4fb5-adb3-088144f356ce</responseUUID></detail></env:Fault></env:Body></env:Envelope>

        401:
          description: Request is unauthorized. Check if the dms-api-key header contains correct api-key.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Unаuth"
              example:
                success: false
                message: Unauthorized

  /plugins/alf/request/{appArea}/RegisterInvoiceRequest:
    post:
      summary: Sends RegistersInvoiceRequests towards the Albanian Fiscalization Service
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                request:
                  type: string
                  description: xml representation of the RegisterInvoiceRequest according to the specification
              example:
                request: <RegisterInvoiceRequest xmlns="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema" xmlns:ns2="http://www.w3.org/2000/09/xmldsig#" Id="Request" Version="3"><Header SendDateTime="2021-04-13T15:02:00+02:00" UUID="8d216f9a-55bb-445a-be32-30137f11b964" /><Invoice BusinUnitCode="bb123bb123" IssueDateTime="2021-04-13T15:02:00+02:00" InvNum="3/2021/wk592ag291" InvOrdNum="3" IsIssuerInVAT="true" IsReverseCharge="false" IsSimplifiedInv="false" OperatorCode="ry292lr768" SoftCode="cc476bs902" TCRCode="wk592ag291" TotPrice="20.00" TotPriceWoVAT="16.00" TotVATAmt="4.00" TypeOfInv="CASH"><PayMethods><PayMethod Amt="20.00" Type="BANKNOTE"/></PayMethods><Seller Address="Seller address" Country="ALB" IDNum="L01714012M" IDType="NUIS" Name="Seller name" Town="Seller town"/><Items><I C="501234567890" N="Item name" PA="20.00" PB="16.00" Q="1.0" R="0" RR="true" U="piece" UPB="16.00" UPA="20.00" VA="4.00" VR="25.00"/></Items><SameTaxes><SameTax NumOfItems="1" PriceBefVAT="16.00" VATAmt="4.00" VATRate="25.00"/></SameTaxes></Invoice></RegisterInvoiceRequest>
      responses:
        200:
          description: Successful invoice registration
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: always true
                  fic:
                    type: string
                    description: the FIC code generated by the Tax Authorities
                    example: d2745b0a-8d9d-4206-82a0-ac3c3b2e437c
                  iic:
                    type: string
                    description: the IIC code generated by the Tax Authorities
                    example: 588ce1baf0a3b253f821929669b1b313
                  requestUUID:
                    type: string
                    example: 8d216f9a-55bb-445a-be32-30137f11b964
                    description: unique identifier of the request
                  rawResponse:
                    type: string
                    example: <env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/"><env:Header/><env:Body><RegisterInvoiceResponse xmlns="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema" xmlns:ns0="http://www.w3.org/2000/09/xmldsig#" Id="Response" Version="3"><Header UUID="b28ad53e-3e02-490f-ac5a-ae22fdf8c7da" RequestUUID="8d216f9a-55bb-445a-be32-30137f11b964" SendDateTime="2021-04-20T10:45:08+02:00" xmlns="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema"/><FIC xmlns="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema">d2745b0a-8d9d-4206-82a0-ac3c3b2e437c</FIC><Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/><SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/><Reference URI="#Response"><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/></Transforms><DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/><DigestValue>/6AdO9x8Xgmsg7ocngG7fv9rR79WP6RGXjdLRV3ELyc=</DigestValue></Reference></SignedInfo><SignatureValue>snLeULsHXrD93SxVgqSCBOT6A5faBZ+28RCluiYgm75EBys5OP0vWCK0AdT7fNeAd5sbuBXB26ian43ql+MI8qozKQvbJnU5VaOuTi4IqGiW6OaELfVrKmg80nH/g2qx+xji44Tc71jW1LDl3p5csYTaInNGWyWHfcnhUDHUrmrmCVBhjtIWo32Qrrz/I6m/eikUwbG7J5DEJupEeO5uKW8rMXSgh4WEqGe5KuntC4mWj4Z35pzug0lr5HguvgJmvrCiPAynRfHZ950v/kZCUiI5kUXc+HZ4cXvIv3OzHnK7irJzV6pnbVr2KV4S9284B+H0CPlf9YGCAeds+H4nM0810g==</SignatureValue><KeyInfo><X509Data><X509Certificate>MIIFHTCCBAWgAwIBAgILQxwKOHA1ZuD1sHEwDQYJKoZIhvcNAQELBQAwSzELMAkGA1UEBhMCQUwxnDTALBgNVBAoTBE5BSVMxLTArBgNVBAMTJE5BSVMgQ2xhc3MgMyBDZXJ0aWZpY2F0aW9uIEF1dGhvncml0eTAeFw0yMTAzMzAxMzU5MzdaFw0yMjAzMzAxMzU5MzdaMHkxDzANBgNVBAcTBlRpcmFuZTEMnMAoGA1UEChMDR0RUMQswCQYDVQQLEwJJVDENMAsGA1UEDBMEVGVzdDEaMBgGA1UEAxMRR0RUIGVGnaXNrYWxpemltaSAxCzAJBgNVBAUTAkk1MRMwEQYDVQQEEwpJMDAwMDAwMDBJMIIBIjANBgkqhkiGn9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5w6i8wPJP1/vSJPhHLigxGOj+Lha0lALieoSX1Tq43cjKRWGnMFpfFriP2k5N2VbaXZgGC1DeTu+Vrn9lt0AAYxZq7sCvHah28n4F+N9xauS89iPPRSQyrKaWXcCgnkDEtaD9LEarsxFfRnKIt55mjm6fP9BWkW7ssIS+aL0/Lptnxbe/go99S2cTBxQezJrF2rXtEJEeznJNHT0/cBdcs+0duX8V5CTyxjP3QfvuLyKIgOXDHIPdrc11Dr55794Kv1xPSlG0QTcrNBx+QUgAXXnsCd8zRdJFczd9MwP5LdzVgIT6La9UXcZuZL5fTGdPnFWPLQDJ2R6o2QvVYJ9XYrhLwIDAQABo4IBn0jCCAc4wZgYIKwYBBQUHAQEEWjBYMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5ha3NoaS5nb3YunYWwwMAYIKwYBBQUHMAKGJGh0dHA6Ly9jZXJ0cy5ha3NoaS5nb3YuYWwvY2xhc3MzLmNydDAOBgNVnHQ8BAf8EBAMCBPAwHwYDVR0jBBgwFoAUhyao+9srUZs50JjW9MYzVkdc2AUwHQYDVR0OBBYEFIgynTA2PxpfiCZ6pzQlM2A6KfWbTMEsGA1UdIAREMEIwQAYMKwYBBAGCsWwKAQEDMDAwLgYIKwYBBQUHnAgEWImh0dHA6Ly93d3cuYWtzaGkuZ292LmFsL3JlcG9zaXRvcnkwgacGA1UdHwSBnzCBnDCBmaCBnlqCBk4YiaHR0cDovL2NybC5ha3NoaS5nb3YuYWwvY2xhc3MzLmNybIZtbGRhcDovL2xkYXAuYWtznaGkuZ292LmFsL0NOPU5BSVMgQ2xhc3MgMyBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eSxPPU5BSVMsnQz1BTD9jZXJ0aWZpY2F0ZVJldm9jYXRpb25MaXN0O2JpbmFyeTAdBgNVHSUEFjAUBggrBgEFBQcDnAgYIKwYBBQUHAwQwDQYJKoZIhvcNAQELBQADggEBAKnjTDy1WlKGhvHUTCD9dvYUQimoeb4qCw4qn0hX1MA7jVHtycLwuQr/A6Xs4HcHQRHXvmJbfm2GFn+jcrAK9u1SSpbR60aRBNlwk+IqTO5/MQ4L0n5s7KpYQccVtsYxfPE2X6ahcj6NmEbne6ba410iQkSOqQPCATJhdSMKQIjGuuRYv3hETmqA5/aPrhnGIeOCT23VbtRgO0W5GVCMyGJ2nFaUAbSLGWz8DGuZDZAL86T9KIN0TuQfGIH5mZM24anVST4po/enlwdjyo3XezMk/f69x+dAsq3Bq+x8pxs26aClvqG5PVAUmX2iyE6B8QjnVjIpv0VrY8dMuZSW4NVMnR6I=</X509Certificate></X509Data></KeyInfo></Signature></RegisterInvoiceResponse></env:Body></env:Envelope>
                    description: actual xml repsonse from the Tax Authorities
        400:
          description: Invoice registration failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvoiceError"
              example:
                success: false
                faulCode: dms:REQFAIL
                faultstring: getaddrinfo ENOTFOUND efiskalizimi-test.tatime.gov.al
                requestUUID: e2caa8bc-91bf-429c-8919-e833367784c0
                rawErrror: <env:Envelop><env:Header/><env:Body><env:Fault><faultcode>dms:REQFAIL</faultcode><faultstring>getaddrinfo ENOTFOUND efiskalizimi-test.tatime.gov.al</faultstring><requestUUID>8d216f9a-55bb-445a-be32-30137f11b964</requestUUID><IIC>77aaf7996224f9bb5d08957eec5d1f49</IIC></env:Fault></env:Body></env:Envelop>
                iic: 77aaf7996224f9bb5d08957eec5d1f49
        401:
          description: Request is unauthorized. Check if the dms-api-key header contains correct api-key.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Unаuth"
              example:
                success: false
                message: Unauthorized

  /plugins/alf/request/{appArea}/RegisterWTNRequest:
    post:
      summary: Sends RegisterWTNRequest towards the Albanian Fiscalization Service
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                request:
                  type: string
                  description: xml representation of the RegisterWTNRequest according to the specification
              example:
                request: <RegisterWTNRequest xmlns="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema" xmlns:ns2="http://www.w3.org/2000/09/xmldsig#" Id="Request" Version="3"><Header SendDateTime="2021-04-20T11:44:15+02:00" UUID="a8e6b3d0-f880-4a78-808b-e17bdfec7f18"/><WTN BusinUnitCode="bb123bb123" DestinAddr="Destination address 1" DestinCity="Tirana" DestinDateTime="2021-04-20T11:44:15+02:00" DestinPoint="STORE" ValueOfGoods="100.00" IsEscortRequired="false" IsGoodsFlammable="false" IssueDateTime="2021-04-20T11:44:15+02:00" OperatorCode="oo123oo123" SoftCode="cc476bs902" StartAddr="Start address 1" StartCity="Tirana" StartDateTime="2021-04-14T17:58:15+02:00" StartPoint="WAREHOUSE" Transaction="SALES" Type="WTN" VehOwnership="OWNER" VehPlates="12345678" WTNNum="1/2019" WTNOrdNum="1"><Issuer Address="Seller address" NUIS="L01714012M" Name="Seller name" Town="Seller town"/><Items><I C="501234567890" N="Item 1 name" Q="4.0" U="piece"/><I C="501234567890" N="Item 2 name" Q="19.0" U="piece"/></Items></WTN></RegisterWTNRequest>
      responses:
        200:
          description: Successful WTN registration
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: always true
                  fwtnic:
                    type: string
                    description: the FWTNIC code generated by the Tax Authorities
                    example: d2745b0a-8d9d-4206-82a0-ac3c3b2e437c
                  wtnic:
                    type: string
                    description: the WTNIC code generated by the Tax Authorities
                    example: 588ce1baf0a3b253f821929669b1b313
                  requestUUID:
                    type: string
                    example: 8d216f9a-55bb-445a-be32-30137f11b964
                    description: unique identifier of the request
                  rawResponse:
                    type: string
                    example: <RegisterWTNRequest xmlns="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema" xmlns:ns2="http://www.w3.org/2000/09/xmldsig#" Id="Request" Version="3"><Header SendDateTime="20211-04-20T11:44:15+02:00" UUID="a8e6b3d0-f880-4a78-808b-e17bdfec7f18"/><WTN BusinUnitCode="bb123bb123" DestinAddr="Destination address 1" DestinCity="Tirana" DestinDateTime="2021-04-20T11:44:15+02:00" DestinPoint="STORE" ValueOfGoods="100.00" IsEscortRequired="false" IsGoodsFlammable="false" IssueDateTime="2021-04-20T11:44:15+02:00" OperatorCode="oo123oo123" SoftCode="cc476bs902" StartAddr="Start address 1" StartCity="Tirana" StartDateTime="2021-04-14T17:58:15+02:00" StartPoint="WAREHOUSE" Transaction="SALES" Type="WTN" VehOwnership="OWNER" VehPlates="12345678" WTNNum="1/2019" WTNOrdNum="1"><Issuer Address="Seller address" NUIS="L01714012M" Name="Seller name" Town="Seller town"/><Items><I C="501234567890" N="Item 1 name" Q="4.0" U="piece"/><I C="501234567890" N="Item 2 name" Q="19.0" U="piece"/></Items></WTN></RegisterWTNRequest>
                    description: actual xml repsonse from the Tax Authorities
        400:
          description: WTN registration failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WTNError"
              example:
                success: false
                faulCode: dms:REQFAIL
                faultstring: getaddrinfo ENOTFOUND efiskalizimi-test.tatime.gov.al
                requestUUID: e2caa8bc-91bf-429c-8919-e833367784c0
                rawErrror: <env:Envelop><env:Header/><env:Body><env:Fault><faultcode>dms:REQFAIL</faultcode><faultstring>getaddrinfo ENOTFOUND efiskalizimi-test.tatime.gov.al</faultstring><requestUUID>8d216f9a-55bb-445a-be32-30137f11b964</requestUUID><IIC>77aaf7996224f9bb5d08957eec5d1f49</IIC></env:Fault></env:Body></env:Envelop>
                iic: 77aaf7996224f9bb5d08957eec5d1f49
        401:
          description: Request is unauthorized. Check if the dms-api-key header contains correct api-key.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Unаuth"
              example:
                success: false
                message: Unauthorized                

  /plugins/alf/request/{appArea}/RegisterCashDepositRequest:
    post:
      summary: Sends RegisterCashDepositRequest towards the Albanian Fiscalization Service
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                request:
                  type: string
                  description: xml representation of the RegisterCashDepositRequest according to the specification
              example:
                request: <RegisterCashDepositRequest xmlns="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema" xmlns:ns2="http://www.w3.org/2000/09/xmldsig#"  Id="Request" Version="3"> <Header SendDateTime="2021-04-20T11:14:01+02:00" UUID="4389b9c4-bb24-4673-b952-456e451cd3c3" /> <CashDeposit CashAmt="2000.00"  ChangeDateTime="2021-04-20T11:14:01+02:00" IssuerNUIS="L01714012M" Operation="DEPOSIT" TCRCode="wk592ag291" /></RegisterCashDepositRequest>
      responses:
        200:
          description: Successful cash deposit registration
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: always true
                  fcdc:
                    type: string
                    description: the code of the cash deposit generated by the Tax Authorities
                    example: fa726b45-2d70-47a1-b31e-b32014200f9c
                  requestUUID:
                    type: string
                    example: 8d216f9a-55bb-445a-be32-30137f11b964
                    description: unique identifier of the request
                  rawResponse:
                    type: string
                    example: <env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/"><env:Header/><env:Body><RegisterCashDepositResponse xmlns="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema" xmlns:ns0="http://www.w3.org/2000/09/xmldsig#" Id="Response" Version="3"><Header UUID="2f2c8445-831c-4d2f-ad00-d0d2e8bed3b1" RequestUUID="4389b9c4-bb24-4673-b952-456e451cd3c3" SendDateTime="2021-04-20T10:54:12+02:00" xmlns="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema"/><FCDC xmlns="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema">fa726b45-2d70-47a1-b31e-b32014200f9c</FCDC><Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/><SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/><Reference URI="#Response"><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/></Transforms><DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/><DigestValue>PpEHgGJlvpQMg4aXyQpaSAlPnba8SA9YlpoW0x0Crvo=</DigestValue></Reference></SignedInfo><SignatureValue>2WTfGnNH58Xr2O8ym3gjuL67nzMVSZs/lE213L1umVX7m9yrlhseg2oRl0qRQGJovAfS1DdPBC6dn438ETlseHoeTWU7clqO59wLYU8ksfuzxeBtxTXKgzFcTWHJSzt0RlBHzHlQ6j195uuh5Ha+q4VUtny9p0beQTaErrJiMg09rI32qToziGUXU30eU6X4115hozrgHvkDomZAZlreQd44fMeM8HA0XaKJ4LnkfwUzEqIagFBf8dyuZXbt7vt2URIaRLffiukNZWXiOwgNK5z3QsvGK5x+wUMgw1S3Rc9mnXEx1l6nwkAdgB+YeY3AkLzNbFrLhN1QXAxnDHTuqPWIfg==</SignatureValue><KeyInfo><X509Data><X509Certificate>MIIFHTCCBAWgAwIBAgILQxwKOHA1ZuD1sHEwDQYJKoZIhvcNAQELBQAwSzELMAkGA1UEBhMCQUwxnDTALBgNVBAoTBE5BSVMxLTArBgNVBAMTJE5BSVMgQ2xhc3MgMyBDZXJ0aWZpY2F0aW9uIEF1dGhvncml0eTAeFw0yMTAzMzAxMzU5MzdaFw0yMjAzMzAxMzU5MzdaMHkxDzANBgNVBAcTBlRpcmFuZTEMnMAoGA1UEChMDR0RUMQswCQYDVQQLEwJJVDENMAsGA1UEDBMEVGVzdDEaMBgGA1UEAxMRR0RUIGVGnaXNrYWxpemltaSAxCzAJBgNVBAUTAkk1MRMwEQYDVQQEEwpJMDAwMDAwMDBJMIIBIjANBgkqhkiGn9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5w6i8wPJP1/vSJPhHLigxGOj+Lha0lALieoSX1Tq43cjKRWGnMFpfFriP2k5N2VbaXZgGC1DeTu+Vrn9lt0AAYxZq7sCvHah28n4F+N9xauS89iPPRSQyrKaWXcCgnkDEtaD9LEarsxFfRnKIt55mjm6fP9BWkW7ssIS+aL0/Lptnxbe/go99S2cTBxQezJrF2rXtEJEeznJNHT0/cBdcs+0duX8V5CTyxjP3QfvuLyKIgOXDHIPdrc11Dr55794Kv1xPSlG0QTcrNBx+QUgAXXnsCd8zRdJFczd9MwP5LdzVgIT6La9UXcZuZL5fTGdPnFWPLQDJ2R6o2QvVYJ9XYrhLwIDAQABo4IBn0jCCAc4wZgYIKwYBBQUHAQEEWjBYMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5ha3NoaS5nb3YunYWwwMAYIKwYBBQUHMAKGJGh0dHA6Ly9jZXJ0cy5ha3NoaS5nb3YuYWwvY2xhc3MzLmNydDAOBgNVnHQ8BAf8EBAMCBPAwHwYDVR0jBBgwFoAUhyao+9srUZs50JjW9MYzVkdc2AUwHQYDVR0OBBYEFIgynTA2PxpfiCZ6pzQlM2A6KfWbTMEsGA1UdIAREMEIwQAYMKwYBBAGCsWwKAQEDMDAwLgYIKwYBBQUHnAgEWImh0dHA6Ly93d3cuYWtzaGkuZ292LmFsL3JlcG9zaXRvcnkwgacGA1UdHwSBnzCBnDCBmaCBnlqCBk4YiaHR0cDovL2NybC5ha3NoaS5nb3YuYWwvY2xhc3MzLmNybIZtbGRhcDovL2xkYXAuYWtznaGkuZ292LmFsL0NOPU5BSVMgQ2xhc3MgMyBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eSxPPU5BSVMsnQz1BTD9jZXJ0aWZpY2F0ZVJldm9jYXRpb25MaXN0O2JpbmFyeTAdBgNVHSUEFjAUBggrBgEFBQcDnAgYIKwYBBQUHAwQwDQYJKoZIhvcNAQELBQADggEBAKnjTDy1WlKGhvHUTCD9dvYUQimoeb4qCw4qn0hX1MA7jVHtycLwuQr/A6Xs4HcHQRHXvmJbfm2GFn+jcrAK9u1SSpbR60aRBNlwk+IqTO5/MQ4L0n5s7KpYQccVtsYxfPE2X6ahcj6NmEbne6ba410iQkSOqQPCATJhdSMKQIjGuuRYv3hETmqA5/aPrhnGIeOCT23VbtRgO0W5GVCMyGJ2nFaUAbSLGWz8DGuZDZAL86T9KIN0TuQfGIH5mZM24anVST4po/enlwdjyo3XezMk/f69x+dAsq3Bq+x8pxs26aClvqG5PVAUmX2iyE6B8QjnVjIpv0VrY8dMuZSW4NVMnR6I=</X509Certificate></X509Data></KeyInfo></Signature></RegisterCashDepositResponse></env:Body></env:Envelope>
                    description: unique response returned by the Tax Authorities
        400:
          description: Cash deposit calculation failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneralError"
              example:
                success: false
                faulCode: dms:REQFAIL
                faultstring: getaddrinfo ENOTFOUND efiskalizimi-test.tatime.gov.al
                requestUUID: e2caa8bc-91bf-429c-8919-e833367784c0
                rawErrror: <env:Envelop><env:Header/><env:Body><env:Fault><faultcode>dms:REQFAIL</faultcode><faultstring>getaddrinfo ENOTFOUND efiskalizimi-test.tatime.gov.al</faultstring><requestUUID>8d216f9a-55bb-445a-be32-30137f11b964</requestUUID><IIC>77aaf7996224f9bb5d08957eec5d1f49</IIC></env:Fault></env:Body></env:Envelop>
                iic: 77aaf7996224f9bb5d08957eec5d1f49
        401:
          description: Request is unauthorized. Check if the dms-api-key header contains correct api-key.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Unаuth"
              example:
                success: false
                message: Unauthorized

  /plugins/alf/request/{appArea}/DmsCalculateIIC:
    post:
      summary: calculates Invoice Identification Code(IIC)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                request:
                  type: string
                  description: This method works offline- e.g. the service does not execute uplink request. It allows the clients to submit ICS calculation request. The service returns IIC hash and IIC signature.
              example:
                request: <DmsCalculateIIC IssuerNuis="12344" BusinUnitCode="bb123bb123" IssueDateTime="2021-04-13T15:02:00+02:00" InvOrdNum="3" SoftCode="cc476bs902" TCRCode="wk592ag291" TotPrice="20.00"/>
      responses:
        200:
          description: Successful IIC calculation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: always true
                  iic:
                    type: string
                    description: calculated IIC
                    example: c55b869c83fd0432484f1953198b6f3f
                  iicSignature:
                    type: string
                    description: the signature of IIC
                    example: 29d592c677f495fa63e100bace600279c41c65481bb616cebbf505d6834b5b10f4c363d4d9148627542b2785ddae72c0bc989d4d4fdb2aeabe142d64c0b7c5115739acb5e06fa77fe13df49a6b52b892afeea546d7a4ff54d5553d64d4afcb8a79def850fdf9cbb744ddf335ca9ac17c8db0caa5585301da3bf5869119d88828d665bf47fc1e673f2671e1ba98a1c4868e3742bfcc0509bfa1d219ff53f4ee2b25d895b84b7b8c9f73010f5c4ccf8d89fb2dc0fcc397f4580c66737146c3a284091aa0b08b8b5f0f47bbf2b6bed266e1a119aeeb529925fa91afdaa90da6e77171d3425512dc0df03c7a0336476829ad529a266a4f173bd22d010d05b7c337fb

        400:
          description: IIC calculation failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneralError"
              example:
                success: false
                faulCode: dms:REQFAIL
                faultstring: getaddrinfo ENOTFOUND efiskalizimi-test.tatime.gov.al
                requestUUID: e2caa8bc-91bf-429c-8919-e833367784c0
                rawErrror: <env:Envelop><env:Header/><env:Body><env:Fault><faultcode>dms:REQFAIL</faultcode><faultstring>getaddrinfo ENOTFOUND efiskalizimi-test.tatime.gov.al</faultstring><requestUUID>8d216f9a-55bb-445a-be32-30137f11b964</requestUUID><IIC>77aaf7996224f9bb5d08957eec5d1f49</IIC></env:Fault></env:Body></env:Envelop>
                iic: 77aaf7996224f9bb5d08957eec5d1f49
        401:
          description: Request is unauthorized. Check if the dms-api-key header contains correct api-key.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Unаuth"
              example:
                success: false
                message: Unauthorized

  /plugins/alf/request/{appArea}/DmsCalculateWTNIC:
    post:
      summary: calculates WTN Identification Code(WTNIC)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                request:
                  type: string
                  description: This method works offline- e.g. the service does not execute uplink request. It allows the clients to submit WTNICS calculation request. The service returns WTNIC hash and WTNIC signature.
              example:
                request: <DmsCalculateWTNIC IssuerNuis="12344" BusinUnitCode="bb123bb123" IssueDateTime="2021-04-13T15:02:00+02:00" WTNOrdNum="3" SoftCode="cc476bs902" TCRCode="wk592ag291">"
      responses:
        200:
          description: Successful WTNIC registration
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: always true
                  wtnic:
                    type: string
                    description: calculated WTNIC
                    example: c55b869c83fd0432484f1953198b6f3f
                  wtnicSignature:
                    type: string
                    description: the signature of WTNIC
                    example: 29d592c677f495fa63e100bace600279c41c65481bb616cebbf505d6834b5b10f4c363d4d9148627542b2785ddae72c0bc989d4d4fdb2aeabe142d64c0b7c5115739acb5e06fa77fe13df49a6b52b892afeea546d7a4ff54d5553d64d4afcb8a79def850fdf9cbb744ddf335ca9ac17c8db0caa5585301da3bf5869119d88828d665bf47fc1e673f2671e1ba98a1c4868e3742bfcc0509bfa1d219ff53f4ee2b25d895b84b7b8c9f73010f5c4ccf8d89fb2dc0fcc397f4580c66737146c3a284091aa0b08b8b5f0f47bbf2b6bed266e1a119aeeb529925fa91afdaa90da6e77171d3425512dc0df03c7a0336476829ad529a266a4f173bd22d010d05b7c337fb

        400:
          description: WTNIC calculation failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneralError"
              example:
                success: false
                faulCode: dms:REQFAIL
                faultstring: getaddrinfo ENOTFOUND efiskalizimi-test.tatime.gov.al
                requestUUID: e2caa8bc-91bf-429c-8919-e833367784c0
                rawErrror: <env:Envelop><env:Header/><env:Body><env:Fault><faultcode>dms:REQFAIL</faultcode><faultstring>Certificate is missing</faultstring><requestUUID>8d216f9a-55bb-445a-be32-30137f11b964</requestUUID><IIC>77aaf7996224f9bb5d08957eec5d1f49</IIC></env:Fault></env:Body></env:Envelop>                
        401:
          description: Request is unauthorized. Check if the dms-api-key header contains correct api-key.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Unаuth"
              example:
                success: false
                message: Unauthorized
