openapi: "3.0.0"
info:
  title: Dynamics Mobile API
  description: 
  version: 1.0.0
  termsOfService: http://example.com/terms/

servers: 
 - url: http://localhost:5002/api


consumes:
  - application/json
produces:
  - application/json

components:
 securitySchemes:
   ApiKeyAuth:
    type: apiKey
    in: header
    name: dms-api-key
 schemas:
    GeneralError:  
      type: object
      properties:  
       faultCode:
         type: string
         description: the code of the error
       faultstring:
         type: string
         description: description of the error
       requestUUID:
         type: string
         description: unique identifier of the error, which produced the error response     
       rawErrror:   
         type: string
         description: raw representation of the actual error in xml format
    InvoiceError:  
      type: object
      properties:  
       faultCode:
         type: string
         description: the code of the error
       faultstring:
         type: string
         description: description of the error
       requestUUID:
         type: string
         description: unique identifier of the error, which produced the error response     
       rawErrror:   
         type: string
         description: raw representation of the actual error in xml format
       iic:
         type: string
         description: invoice issuer code generated by this middleware even if the remote service returns error
      

security:
  - ApiKeyAuth: []
  
paths:
  /plugins/alf/request/{appArea}/RegisterTCRRequest:
    post:
      summary: Sends RegisterTCRRequest towards the Albanian Fiscalization Service  
      parameters:
        - in: path
          name: appArea
          schema:
            type: string
          required: true
          description: unique identifier of the Dynamics Mobile application area
          example: DEMO01
      requestBody:
       content:
        application/json:
         schema:
          type: object
          properties:
           request:
             type: string
             description: xml representation of the RegisterTCRRequest according to the specification
          example:   
             request: <RegisterTCRRequest xmlns="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema" xmlns:ns2="http://www.w3.org/2000/09/xmldsig#" Id="Request" Version="3"><Header SendDateTime="2021-04-10T08:43:00+02:00" UUID="e2caa8bc-91bf-429c-8919-e833367784c0" /><TCR BusinUnitCode="ge484ak993" IssuerNUIS="L01714012M" MaintainerCode="zk772ct263" SoftCode="cc476bs902" TCRIntID="2" ValidFrom="2021-04-10" Type="REGULAR" /></RegisterTCRRequest>
      responses:
        200:
          description: Successful TCR registration
          content:
           application/json:
            schema:
             type: object
             properties:
              tcrCode:
                type: string
                description: the code of the TCR generated by the Tax Authorities
                example: wk592ag291
              requestUUID:
                type: string
                example: 8d216f9a-55bb-445a-be32-30137f11b964
                description: unique identifier of the request

        400:
          description: TCR registration failed 
          content:
           application/json:
             schema:
              $ref: '#/components/schemas/GeneralError'
             example: 
                faulCode: env:CLIENT                
                faultstring: Client time differs from server time more than 60 minutes, difference is 4747 minutes.
                requestUUID: e2caa8bc-91bf-429c-8919-e833367784c0
                rawErrror: <env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/"><env:Header/><env:Body><env:Fault><faultcode>env:CLIENT</faultcode><faultstring>Client time differs from server time more than 60 minutes, difference is 4747 minutes.</faultstring><detail><code>2</code><requestUUID>e2caa8bc-91bf-429c-8919-e833367784c0</requestUUID><responseUUID>fe8ed7b6-48c7-4fb5-adb3-088144f356ce</responseUUID></detail></env:Fault></env:Body></env:Envelope>   
  
  /plugins/alf/request/{appArea}/RegisterInvoiceRequest:
    post:
      summary: Sends RegistersInvoiceRequests towards the Albanian Fiscalization Service
      requestBody:
       content:
        application/json:
         schema:
          type: object
          properties:
           request:
             type: string
             description: xml representation of the RegisterInvoiceRequest according to the specification
          example:   
             request: <RegisterInvoiceRequest xmlns="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema" xmlns:ns2="http://www.w3.org/2000/09/xmldsig#" Id="Request" Version="3"><Header SendDateTime="2021-04-13T15:02:00+02:00" UUID="8d216f9a-55bb-445a-be32-30137f11b964" /><Invoice BusinUnitCode="bb123bb123" IssueDateTime="2021-04-13T15:02:00+02:00" InvNum="3/2021/wk592ag291" InvOrdNum="3" IsIssuerInVAT="true" IsReverseCharge="false" IsSimplifiedInv="false" OperatorCode="ry292lr768" SoftCode="cc476bs902" TCRCode="wk592ag291" TotPrice="20.00" TotPriceWoVAT="16.00" TotVATAmt="4.00" TypeOfInv="CASH"><PayMethods><PayMethod Amt="20.00" Type="BANKNOTE"/></PayMethods><Seller Address="Seller address" Country="ALB" IDNum="L01714012M" IDType="NUIS" Name="Seller name" Town="Seller town"/><Items><I C="501234567890" N="Item name" PA="20.00" PB="16.00" Q="1.0" R="0" RR="true" U="piece" UPB="16.00" UPA="20.00" VA="4.00" VR="25.00"/></Items><SameTaxes><SameTax NumOfItems="1" PriceBefVAT="16.00" VATAmt="4.00" VATRate="25.00"/></SameTaxes></Invoice></RegisterInvoiceRequest>
      responses:
        200:
          description: Successful invoice registration
        400:
          description: Invoice registration failed 
          content:
           application/json:
             schema:
              $ref: '#/components/schemas/InvoiceError'
             example: 
                faulCode: dms:REQFAIL                
                faultstring: getaddrinfo ENOTFOUND efiskalizimi-test.tatime.gov.al
                requestUUID: e2caa8bc-91bf-429c-8919-e833367784c0
                rawErrror: <env:Envelop><env:Header/><env:Body><env:Fault><faultcode>dms:REQFAIL</faultcode><faultstring>getaddrinfo ENOTFOUND efiskalizimi-test.tatime.gov.al</faultstring><requestUUID>8d216f9a-55bb-445a-be32-30137f11b964</requestUUID><IIC>77aaf7996224f9bb5d08957eec5d1f49</IIC></env:Fault></env:Body></env:Envelop>
                iic: 77aaf7996224f9bb5d08957eec5d1f49

  /plugins/alf/request/{appArea}/RegisterCashDepositRequest:
    post:
      summary: Sends RegisterCashDepositRequest towards the Albanian Fiscalization Service  
      requestBody:
       content:
        application/json:
         schema:
          type: object
          properties:
           request:
             type: string
             description: xml representation of the RegisterCashDepositRequest according to the specification
          example:   
             request: <RegisterCashDepositRequest xmlns="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema" xmlns:ns2="http://www.w3.org/2000/09/xmldsig#" Id="Request" Version="3"><Header SendDateTime="2021-04-10T08:43:00+02:00" UUID="e2caa8bc-91bf-429c-8919-e833367784c0" /><TCR BusinUnitCode="ge484ak993" IssuerNUIS="L01714012M" MaintainerCode="zk772ct263" SoftCode="cc476bs902" TCRIntID="2" ValidFrom="2021-04-10" Type="REGULAR" /></RegisterTCRRequest>
      responses:
       200:
          description: Successful invoice registration
       400:
          description: Invoice registration failed 
          content:
           application/json:
             schema:
              $ref: '#/components/schemas/InvoiceError'
             example: 
                faulCode: dms:REQFAIL                
                faultstring: getaddrinfo ENOTFOUND efiskalizimi-test.tatime.gov.al
                requestUUID: e2caa8bc-91bf-429c-8919-e833367784c0
                rawErrror: <env:Envelop><env:Header/><env:Body><env:Fault><faultcode>dms:REQFAIL</faultcode><faultstring>getaddrinfo ENOTFOUND efiskalizimi-test.tatime.gov.al</faultstring><requestUUID>8d216f9a-55bb-445a-be32-30137f11b964</requestUUID><IIC>77aaf7996224f9bb5d08957eec5d1f49</IIC></env:Fault></env:Body></env:Envelop>
                iic: 77aaf7996224f9bb5d08957eec5d1f49

  /plugins/alf/request/{appArea}/DmsCalculateISC:
    post:
      summary: calculates ISC  
      requestBody:
       content:
        application/json:
         schema:
          type: object
          properties:
           request:
             type: string
             description: xml representation of the RegisterCashDepositRequest according to the specification
          example:   
             request: <RegisterCashDepositRequest xmlns="https://eFiskalizimi.tatime.gov.al/FiscalizationService/schema" xmlns:ns2="http://www.w3.org/2000/09/xmldsig#" Id="Request" Version="3"><Header SendDateTime="2021-04-10T08:43:00+02:00" UUID="e2caa8bc-91bf-429c-8919-e833367784c0" /><TCR BusinUnitCode="ge484ak993" IssuerNUIS="L01714012M" MaintainerCode="zk772ct263" SoftCode="cc476bs902" TCRIntID="2" ValidFrom="2021-04-10" Type="REGULAR" /></RegisterTCRRequest>
      responses:
       200:
          description: Successful invoice registration
       400:
          description: Invoice registration failed 
          content:
           application/json:
             schema:
              $ref: '#/components/schemas/InvoiceError'
             example: 
                faulCode: dms:REQFAIL                
                faultstring: getaddrinfo ENOTFOUND efiskalizimi-test.tatime.gov.al
                requestUUID: e2caa8bc-91bf-429c-8919-e833367784c0
                rawErrror: <env:Envelop><env:Header/><env:Body><env:Fault><faultcode>dms:REQFAIL</faultcode><faultstring>getaddrinfo ENOTFOUND efiskalizimi-test.tatime.gov.al</faultstring><requestUUID>8d216f9a-55bb-445a-be32-30137f11b964</requestUUID><IIC>77aaf7996224f9bb5d08957eec5d1f49</IIC></env:Fault></env:Body></env:Envelop>
                iic: 77aaf7996224f9bb5d08957eec5d1f49                